#ifndef COORDSTOINTERP_H
#define COORDSTOINTERP_H

# include <iostream>
# include "Coords.h"
# include "Interp.h"

# include <unordered_map>

namespace coords2interp{

class CoordsToInterp
{
public:


	interp::PROGRAM* getPROGRAM(coords::PROGRAM* c) const;
	coords::PROGRAM* getPROGRAM(interp::PROGRAM* i) const;

	void putSEQ_GLOBALSTMT(coords::SEQ_GLOBALSTMT* key, interp::SEQ_GLOBALSTMT* val);
	interp::SEQ_GLOBALSTMT* getSEQ_GLOBALSTMT(coords::SEQ_GLOBALSTMT* c) const;
	coords::SEQ_GLOBALSTMT* getSEQ_GLOBALSTMT(interp::SEQ_GLOBALSTMT* i) const;

	interp::GLOBALSTMT* getGLOBALSTMT(coords::GLOBALSTMT* c) const;
	coords::GLOBALSTMT* getGLOBALSTMT(interp::GLOBALSTMT* i) const;

	void putMAIN_STMT(coords::MAIN_STMT* key, interp::MAIN_STMT* val);
	interp::MAIN_STMT* getMAIN_STMT(coords::MAIN_STMT* c) const;
	coords::MAIN_STMT* getMAIN_STMT(interp::MAIN_STMT* i) const;

	void putFUNCTION_STMT(coords::FUNCTION_STMT* key, interp::FUNCTION_STMT* val);
	interp::FUNCTION_STMT* getFUNCTION_STMT(coords::FUNCTION_STMT* c) const;
	coords::FUNCTION_STMT* getFUNCTION_STMT(interp::FUNCTION_STMT* i) const;

	interp::STMT* getSTMT(coords::STMT* c) const;
	coords::STMT* getSTMT(interp::STMT* i) const;

	void putCOMPOUND_STMT(coords::COMPOUND_STMT* key, interp::COMPOUND_STMT* val);
	interp::COMPOUND_STMT* getCOMPOUND_STMT(coords::COMPOUND_STMT* c) const;
	coords::COMPOUND_STMT* getCOMPOUND_STMT(interp::COMPOUND_STMT* i) const;

	interp::IFCOND* getIFCOND(coords::IFCOND* c) const;
	coords::IFCOND* getIFCOND(interp::IFCOND* i) const;

	void putIFTHEN_EXPR_STMT(coords::IFTHEN_EXPR_STMT* key, interp::IFTHEN_EXPR_STMT* val);
	interp::IFTHEN_EXPR_STMT* getIFTHEN_EXPR_STMT(coords::IFTHEN_EXPR_STMT* c) const;
	coords::IFTHEN_EXPR_STMT* getIFTHEN_EXPR_STMT(interp::IFTHEN_EXPR_STMT* i) const;

	void putIFTHENELSEIF_EXPR_STMT_IFCOND(coords::IFTHENELSEIF_EXPR_STMT_IFCOND* key, interp::IFTHENELSEIF_EXPR_STMT_IFCOND* val);
	interp::IFTHENELSEIF_EXPR_STMT_IFCOND* getIFTHENELSEIF_EXPR_STMT_IFCOND(coords::IFTHENELSEIF_EXPR_STMT_IFCOND* c) const;
	coords::IFTHENELSEIF_EXPR_STMT_IFCOND* getIFTHENELSEIF_EXPR_STMT_IFCOND(interp::IFTHENELSEIF_EXPR_STMT_IFCOND* i) const;

	void putIFTHENELSE_EXPR_STMT_STMT(coords::IFTHENELSE_EXPR_STMT_STMT* key, interp::IFTHENELSE_EXPR_STMT_STMT* val);
	interp::IFTHENELSE_EXPR_STMT_STMT* getIFTHENELSE_EXPR_STMT_STMT(coords::IFTHENELSE_EXPR_STMT_STMT* c) const;
	coords::IFTHENELSE_EXPR_STMT_STMT* getIFTHENELSE_EXPR_STMT_STMT(interp::IFTHENELSE_EXPR_STMT_STMT* i) const;

	interp::EXPR* getEXPR(coords::EXPR* c) const;
	coords::EXPR* getEXPR(interp::EXPR* i) const;

	interp::ASSIGNMENT* getASSIGNMENT(coords::ASSIGNMENT* c) const;
	coords::ASSIGNMENT* getASSIGNMENT(interp::ASSIGNMENT* i) const;

	void putASSIGN_REAL1_VAR_REAL1_EXPR(coords::ASSIGN_REAL1_VAR_REAL1_EXPR* key, interp::ASSIGN_REAL1_VAR_REAL1_EXPR* val);
	interp::ASSIGN_REAL1_VAR_REAL1_EXPR* getASSIGN_REAL1_VAR_REAL1_EXPR(coords::ASSIGN_REAL1_VAR_REAL1_EXPR* c) const;
	coords::ASSIGN_REAL1_VAR_REAL1_EXPR* getASSIGN_REAL1_VAR_REAL1_EXPR(interp::ASSIGN_REAL1_VAR_REAL1_EXPR* i) const;

	void putASSIGN_REAL3_VAR_REAL3_EXPR(coords::ASSIGN_REAL3_VAR_REAL3_EXPR* key, interp::ASSIGN_REAL3_VAR_REAL3_EXPR* val);
	interp::ASSIGN_REAL3_VAR_REAL3_EXPR* getASSIGN_REAL3_VAR_REAL3_EXPR(coords::ASSIGN_REAL3_VAR_REAL3_EXPR* c) const;
	coords::ASSIGN_REAL3_VAR_REAL3_EXPR* getASSIGN_REAL3_VAR_REAL3_EXPR(interp::ASSIGN_REAL3_VAR_REAL3_EXPR* i) const;

	void putASSIGN_REAL4_VAR_REAL4_EXPR(coords::ASSIGN_REAL4_VAR_REAL4_EXPR* key, interp::ASSIGN_REAL4_VAR_REAL4_EXPR* val);
	interp::ASSIGN_REAL4_VAR_REAL4_EXPR* getASSIGN_REAL4_VAR_REAL4_EXPR(coords::ASSIGN_REAL4_VAR_REAL4_EXPR* c) const;
	coords::ASSIGN_REAL4_VAR_REAL4_EXPR* getASSIGN_REAL4_VAR_REAL4_EXPR(interp::ASSIGN_REAL4_VAR_REAL4_EXPR* i) const;

	void putASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR(coords::ASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR* key, interp::ASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR* val);
	interp::ASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR* getASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR(coords::ASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR* c) const;
	coords::ASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR* getASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR(interp::ASSIGN_REALMATRIX_VAR_REALMATRIX_EXPR* i) const;

	interp::DECLARE* getDECLARE(coords::DECLARE* c) const;
	coords::DECLARE* getDECLARE(interp::DECLARE* i) const;

	void putDECL_REAL1_VAR_REAL1_EXPR(coords::DECL_REAL1_VAR_REAL1_EXPR* key, interp::DECL_REAL1_VAR_REAL1_EXPR* val);
	interp::DECL_REAL1_VAR_REAL1_EXPR* getDECL_REAL1_VAR_REAL1_EXPR(coords::DECL_REAL1_VAR_REAL1_EXPR* c) const;
	coords::DECL_REAL1_VAR_REAL1_EXPR* getDECL_REAL1_VAR_REAL1_EXPR(interp::DECL_REAL1_VAR_REAL1_EXPR* i) const;

	void putDECL_REAL3_VAR_REAL3_EXPR(coords::DECL_REAL3_VAR_REAL3_EXPR* key, interp::DECL_REAL3_VAR_REAL3_EXPR* val);
	interp::DECL_REAL3_VAR_REAL3_EXPR* getDECL_REAL3_VAR_REAL3_EXPR(coords::DECL_REAL3_VAR_REAL3_EXPR* c) const;
	coords::DECL_REAL3_VAR_REAL3_EXPR* getDECL_REAL3_VAR_REAL3_EXPR(interp::DECL_REAL3_VAR_REAL3_EXPR* i) const;

	void putDECL_REAL4_VAR_REAL4_EXPR(coords::DECL_REAL4_VAR_REAL4_EXPR* key, interp::DECL_REAL4_VAR_REAL4_EXPR* val);
	interp::DECL_REAL4_VAR_REAL4_EXPR* getDECL_REAL4_VAR_REAL4_EXPR(coords::DECL_REAL4_VAR_REAL4_EXPR* c) const;
	coords::DECL_REAL4_VAR_REAL4_EXPR* getDECL_REAL4_VAR_REAL4_EXPR(interp::DECL_REAL4_VAR_REAL4_EXPR* i) const;

	void putDECL_REALMATRIX_VAR_REALMATRIX_EXPR(coords::DECL_REALMATRIX_VAR_REALMATRIX_EXPR* key, interp::DECL_REALMATRIX_VAR_REALMATRIX_EXPR* val);
	interp::DECL_REALMATRIX_VAR_REALMATRIX_EXPR* getDECL_REALMATRIX_VAR_REALMATRIX_EXPR(coords::DECL_REALMATRIX_VAR_REALMATRIX_EXPR* c) const;
	coords::DECL_REALMATRIX_VAR_REALMATRIX_EXPR* getDECL_REALMATRIX_VAR_REALMATRIX_EXPR(interp::DECL_REALMATRIX_VAR_REALMATRIX_EXPR* i) const;

	void putDECL_REAL1_VAR(coords::DECL_REAL1_VAR* key, interp::DECL_REAL1_VAR* val);
	interp::DECL_REAL1_VAR* getDECL_REAL1_VAR(coords::DECL_REAL1_VAR* c) const;
	coords::DECL_REAL1_VAR* getDECL_REAL1_VAR(interp::DECL_REAL1_VAR* i) const;

	void putDECL_REAL3_VAR(coords::DECL_REAL3_VAR* key, interp::DECL_REAL3_VAR* val);
	interp::DECL_REAL3_VAR* getDECL_REAL3_VAR(coords::DECL_REAL3_VAR* c) const;
	coords::DECL_REAL3_VAR* getDECL_REAL3_VAR(interp::DECL_REAL3_VAR* i) const;

	void putDECL_REAL4_VAR(coords::DECL_REAL4_VAR* key, interp::DECL_REAL4_VAR* val);
	interp::DECL_REAL4_VAR* getDECL_REAL4_VAR(coords::DECL_REAL4_VAR* c) const;
	coords::DECL_REAL4_VAR* getDECL_REAL4_VAR(interp::DECL_REAL4_VAR* i) const;

	void putDECL_REALMATRIX_VAR(coords::DECL_REALMATRIX_VAR* key, interp::DECL_REALMATRIX_VAR* val);
	interp::DECL_REALMATRIX_VAR* getDECL_REALMATRIX_VAR(coords::DECL_REALMATRIX_VAR* c) const;
	coords::DECL_REALMATRIX_VAR* getDECL_REALMATRIX_VAR(interp::DECL_REALMATRIX_VAR* i) const;

	interp::REAL1_EXPR* getREAL1_EXPR(coords::REAL1_EXPR* c) const;
	coords::REAL1_EXPR* getREAL1_EXPR(interp::REAL1_EXPR* i) const;

	void putPAREN_REAL1_EXPR(coords::PAREN_REAL1_EXPR* key, interp::PAREN_REAL1_EXPR* val);
	interp::PAREN_REAL1_EXPR* getPAREN_REAL1_EXPR(coords::PAREN_REAL1_EXPR* c) const;
	coords::PAREN_REAL1_EXPR* getPAREN_REAL1_EXPR(interp::PAREN_REAL1_EXPR* i) const;

	void putINV_REAL1_EXPR(coords::INV_REAL1_EXPR* key, interp::INV_REAL1_EXPR* val);
	interp::INV_REAL1_EXPR* getINV_REAL1_EXPR(coords::INV_REAL1_EXPR* c) const;
	coords::INV_REAL1_EXPR* getINV_REAL1_EXPR(interp::INV_REAL1_EXPR* i) const;

	void putNEG_REAL1_EXPR(coords::NEG_REAL1_EXPR* key, interp::NEG_REAL1_EXPR* val);
	interp::NEG_REAL1_EXPR* getNEG_REAL1_EXPR(coords::NEG_REAL1_EXPR* c) const;
	coords::NEG_REAL1_EXPR* getNEG_REAL1_EXPR(interp::NEG_REAL1_EXPR* i) const;

	void putADD_REAL1_EXPR_REAL1_EXPR(coords::ADD_REAL1_EXPR_REAL1_EXPR* key, interp::ADD_REAL1_EXPR_REAL1_EXPR* val);
	interp::ADD_REAL1_EXPR_REAL1_EXPR* getADD_REAL1_EXPR_REAL1_EXPR(coords::ADD_REAL1_EXPR_REAL1_EXPR* c) const;
	coords::ADD_REAL1_EXPR_REAL1_EXPR* getADD_REAL1_EXPR_REAL1_EXPR(interp::ADD_REAL1_EXPR_REAL1_EXPR* i) const;

	void putSUB_REAL1_EXPR_REAL1_EXPR(coords::SUB_REAL1_EXPR_REAL1_EXPR* key, interp::SUB_REAL1_EXPR_REAL1_EXPR* val);
	interp::SUB_REAL1_EXPR_REAL1_EXPR* getSUB_REAL1_EXPR_REAL1_EXPR(coords::SUB_REAL1_EXPR_REAL1_EXPR* c) const;
	coords::SUB_REAL1_EXPR_REAL1_EXPR* getSUB_REAL1_EXPR_REAL1_EXPR(interp::SUB_REAL1_EXPR_REAL1_EXPR* i) const;

	void putMUL_REAL1_EXPR_REAL1_EXPR(coords::MUL_REAL1_EXPR_REAL1_EXPR* key, interp::MUL_REAL1_EXPR_REAL1_EXPR* val);
	interp::MUL_REAL1_EXPR_REAL1_EXPR* getMUL_REAL1_EXPR_REAL1_EXPR(coords::MUL_REAL1_EXPR_REAL1_EXPR* c) const;
	coords::MUL_REAL1_EXPR_REAL1_EXPR* getMUL_REAL1_EXPR_REAL1_EXPR(interp::MUL_REAL1_EXPR_REAL1_EXPR* i) const;

	void putDIV_REAL1_EXPR_REAL1_EXPR(coords::DIV_REAL1_EXPR_REAL1_EXPR* key, interp::DIV_REAL1_EXPR_REAL1_EXPR* val);
	interp::DIV_REAL1_EXPR_REAL1_EXPR* getDIV_REAL1_EXPR_REAL1_EXPR(coords::DIV_REAL1_EXPR_REAL1_EXPR* c) const;
	coords::DIV_REAL1_EXPR_REAL1_EXPR* getDIV_REAL1_EXPR_REAL1_EXPR(interp::DIV_REAL1_EXPR_REAL1_EXPR* i) const;

	void putREF_REAL1_VAR(coords::REF_REAL1_VAR* key, interp::REF_REAL1_VAR* val);
	interp::REF_REAL1_VAR* getREF_REAL1_VAR(coords::REF_REAL1_VAR* c) const;
	coords::REF_REAL1_VAR* getREF_REAL1_VAR(interp::REF_REAL1_VAR* i) const;

	interp::REAL3_EXPR* getREAL3_EXPR(coords::REAL3_EXPR* c) const;
	coords::REAL3_EXPR* getREAL3_EXPR(interp::REAL3_EXPR* i) const;

	void putPAREN_REAL3_EXPR(coords::PAREN_REAL3_EXPR* key, interp::PAREN_REAL3_EXPR* val);
	interp::PAREN_REAL3_EXPR* getPAREN_REAL3_EXPR(coords::PAREN_REAL3_EXPR* c) const;
	coords::PAREN_REAL3_EXPR* getPAREN_REAL3_EXPR(interp::PAREN_REAL3_EXPR* i) const;

	void putADD_REAL3_EXPR_REAL3_EXPR(coords::ADD_REAL3_EXPR_REAL3_EXPR* key, interp::ADD_REAL3_EXPR_REAL3_EXPR* val);
	interp::ADD_REAL3_EXPR_REAL3_EXPR* getADD_REAL3_EXPR_REAL3_EXPR(coords::ADD_REAL3_EXPR_REAL3_EXPR* c) const;
	coords::ADD_REAL3_EXPR_REAL3_EXPR* getADD_REAL3_EXPR_REAL3_EXPR(interp::ADD_REAL3_EXPR_REAL3_EXPR* i) const;

	void putSUB_REAL3_EXPR_REAL3_EXPR(coords::SUB_REAL3_EXPR_REAL3_EXPR* key, interp::SUB_REAL3_EXPR_REAL3_EXPR* val);
	interp::SUB_REAL3_EXPR_REAL3_EXPR* getSUB_REAL3_EXPR_REAL3_EXPR(coords::SUB_REAL3_EXPR_REAL3_EXPR* c) const;
	coords::SUB_REAL3_EXPR_REAL3_EXPR* getSUB_REAL3_EXPR_REAL3_EXPR(interp::SUB_REAL3_EXPR_REAL3_EXPR* i) const;

	void putINV_REAL3_EXPR(coords::INV_REAL3_EXPR* key, interp::INV_REAL3_EXPR* val);
	interp::INV_REAL3_EXPR* getINV_REAL3_EXPR(coords::INV_REAL3_EXPR* c) const;
	coords::INV_REAL3_EXPR* getINV_REAL3_EXPR(interp::INV_REAL3_EXPR* i) const;

	void putNEG_REAL3_EXPR(coords::NEG_REAL3_EXPR* key, interp::NEG_REAL3_EXPR* val);
	interp::NEG_REAL3_EXPR* getNEG_REAL3_EXPR(coords::NEG_REAL3_EXPR* c) const;
	coords::NEG_REAL3_EXPR* getNEG_REAL3_EXPR(interp::NEG_REAL3_EXPR* i) const;

	void putMUL_REAL3_EXPR_REAL1_EXPR(coords::MUL_REAL3_EXPR_REAL1_EXPR* key, interp::MUL_REAL3_EXPR_REAL1_EXPR* val);
	interp::MUL_REAL3_EXPR_REAL1_EXPR* getMUL_REAL3_EXPR_REAL1_EXPR(coords::MUL_REAL3_EXPR_REAL1_EXPR* c) const;
	coords::MUL_REAL3_EXPR_REAL1_EXPR* getMUL_REAL3_EXPR_REAL1_EXPR(interp::MUL_REAL3_EXPR_REAL1_EXPR* i) const;

	void putMUL_REALMATRIX_EXPR_REAL3_EXPR(coords::MUL_REALMATRIX_EXPR_REAL3_EXPR* key, interp::MUL_REALMATRIX_EXPR_REAL3_EXPR* val);
	interp::MUL_REALMATRIX_EXPR_REAL3_EXPR* getMUL_REALMATRIX_EXPR_REAL3_EXPR(coords::MUL_REALMATRIX_EXPR_REAL3_EXPR* c) const;
	coords::MUL_REALMATRIX_EXPR_REAL3_EXPR* getMUL_REALMATRIX_EXPR_REAL3_EXPR(interp::MUL_REALMATRIX_EXPR_REAL3_EXPR* i) const;

	void putDIV_REAL3_EXPR_REAL1_EXPR(coords::DIV_REAL3_EXPR_REAL1_EXPR* key, interp::DIV_REAL3_EXPR_REAL1_EXPR* val);
	interp::DIV_REAL3_EXPR_REAL1_EXPR* getDIV_REAL3_EXPR_REAL1_EXPR(coords::DIV_REAL3_EXPR_REAL1_EXPR* c) const;
	coords::DIV_REAL3_EXPR_REAL1_EXPR* getDIV_REAL3_EXPR_REAL1_EXPR(interp::DIV_REAL3_EXPR_REAL1_EXPR* i) const;

	void putREF_REAL3_VAR(coords::REF_REAL3_VAR* key, interp::REF_REAL3_VAR* val);
	interp::REF_REAL3_VAR* getREF_REAL3_VAR(coords::REF_REAL3_VAR* c) const;
	coords::REF_REAL3_VAR* getREF_REAL3_VAR(interp::REF_REAL3_VAR* i) const;

	interp::REAL4_EXPR* getREAL4_EXPR(coords::REAL4_EXPR* c) const;
	coords::REAL4_EXPR* getREAL4_EXPR(interp::REAL4_EXPR* i) const;

	void putPAREN_REAL4_EXPR(coords::PAREN_REAL4_EXPR* key, interp::PAREN_REAL4_EXPR* val);
	interp::PAREN_REAL4_EXPR* getPAREN_REAL4_EXPR(coords::PAREN_REAL4_EXPR* c) const;
	coords::PAREN_REAL4_EXPR* getPAREN_REAL4_EXPR(interp::PAREN_REAL4_EXPR* i) const;

	void putADD_REAL4_EXPR_REAL4_EXPR(coords::ADD_REAL4_EXPR_REAL4_EXPR* key, interp::ADD_REAL4_EXPR_REAL4_EXPR* val);
	interp::ADD_REAL4_EXPR_REAL4_EXPR* getADD_REAL4_EXPR_REAL4_EXPR(coords::ADD_REAL4_EXPR_REAL4_EXPR* c) const;
	coords::ADD_REAL4_EXPR_REAL4_EXPR* getADD_REAL4_EXPR_REAL4_EXPR(interp::ADD_REAL4_EXPR_REAL4_EXPR* i) const;

	void putMUL_REAL4_EXPR_REAL1_EXPR(coords::MUL_REAL4_EXPR_REAL1_EXPR* key, interp::MUL_REAL4_EXPR_REAL1_EXPR* val);
	interp::MUL_REAL4_EXPR_REAL1_EXPR* getMUL_REAL4_EXPR_REAL1_EXPR(coords::MUL_REAL4_EXPR_REAL1_EXPR* c) const;
	coords::MUL_REAL4_EXPR_REAL1_EXPR* getMUL_REAL4_EXPR_REAL1_EXPR(interp::MUL_REAL4_EXPR_REAL1_EXPR* i) const;

	void putREF_REAL4_VAR(coords::REF_REAL4_VAR* key, interp::REF_REAL4_VAR* val);
	interp::REF_REAL4_VAR* getREF_REAL4_VAR(coords::REF_REAL4_VAR* c) const;
	coords::REF_REAL4_VAR* getREF_REAL4_VAR(interp::REF_REAL4_VAR* i) const;

	interp::REALMATRIX_EXPR* getREALMATRIX_EXPR(coords::REALMATRIX_EXPR* c) const;
	coords::REALMATRIX_EXPR* getREALMATRIX_EXPR(interp::REALMATRIX_EXPR* i) const;

	void putPAREN_REALMATRIX_EXPR(coords::PAREN_REALMATRIX_EXPR* key, interp::PAREN_REALMATRIX_EXPR* val);
	interp::PAREN_REALMATRIX_EXPR* getPAREN_REALMATRIX_EXPR(coords::PAREN_REALMATRIX_EXPR* c) const;
	coords::PAREN_REALMATRIX_EXPR* getPAREN_REALMATRIX_EXPR(interp::PAREN_REALMATRIX_EXPR* i) const;

	void putMUL_REALMATRIX_EXPR_REALMATRIX_EXPR(coords::MUL_REALMATRIX_EXPR_REALMATRIX_EXPR* key, interp::MUL_REALMATRIX_EXPR_REALMATRIX_EXPR* val);
	interp::MUL_REALMATRIX_EXPR_REALMATRIX_EXPR* getMUL_REALMATRIX_EXPR_REALMATRIX_EXPR(coords::MUL_REALMATRIX_EXPR_REALMATRIX_EXPR* c) const;
	coords::MUL_REALMATRIX_EXPR_REALMATRIX_EXPR* getMUL_REALMATRIX_EXPR_REALMATRIX_EXPR(interp::MUL_REALMATRIX_EXPR_REALMATRIX_EXPR* i) const;

	void putREF_EXPR_REALMATRIX_VAR(coords::REF_EXPR_REALMATRIX_VAR* key, interp::REF_EXPR_REALMATRIX_VAR* val);
	interp::REF_EXPR_REALMATRIX_VAR* getREF_EXPR_REALMATRIX_VAR(coords::REF_EXPR_REALMATRIX_VAR* c) const;
	coords::REF_EXPR_REALMATRIX_VAR* getREF_EXPR_REALMATRIX_VAR(interp::REF_EXPR_REALMATRIX_VAR* i) const;

	void putREAL1_VAR_IDENT(coords::REAL1_VAR_IDENT* key, interp::REAL1_VAR_IDENT* val);
	interp::REAL1_VAR_IDENT* getREAL1_VAR_IDENT(coords::REAL1_VAR_IDENT* c) const;
	coords::REAL1_VAR_IDENT* getREAL1_VAR_IDENT(interp::REAL1_VAR_IDENT* i) const;

	void putREAL3_VAR_IDENT(coords::REAL3_VAR_IDENT* key, interp::REAL3_VAR_IDENT* val);
	interp::REAL3_VAR_IDENT* getREAL3_VAR_IDENT(coords::REAL3_VAR_IDENT* c) const;
	coords::REAL3_VAR_IDENT* getREAL3_VAR_IDENT(interp::REAL3_VAR_IDENT* i) const;

	void putREAL4_VAR_IDENT(coords::REAL4_VAR_IDENT* key, interp::REAL4_VAR_IDENT* val);
	interp::REAL4_VAR_IDENT* getREAL4_VAR_IDENT(coords::REAL4_VAR_IDENT* c) const;
	coords::REAL4_VAR_IDENT* getREAL4_VAR_IDENT(interp::REAL4_VAR_IDENT* i) const;

	void putREALMATRIX_VAR_IDENT(coords::REALMATRIX_VAR_IDENT* key, interp::REALMATRIX_VAR_IDENT* val);
	interp::REALMATRIX_VAR_IDENT* getREALMATRIX_VAR_IDENT(coords::REALMATRIX_VAR_IDENT* c) const;
	coords::REALMATRIX_VAR_IDENT* getREALMATRIX_VAR_IDENT(interp::REALMATRIX_VAR_IDENT* i) const;

	interp::REAL1_LITERAL* getREAL1_LITERAL(coords::REAL1_LITERAL* c) const;
	coords::REAL1_LITERAL* getREAL1_LITERAL(interp::REAL1_LITERAL* i) const;

	void putREAL1_LITERAL1(coords::REAL1_LITERAL1* key, interp::REAL1_LITERAL1* val);
	interp::REAL1_LITERAL1* getREAL1_LITERAL1(coords::REAL1_LITERAL1* c) const;
	coords::REAL1_LITERAL1* getREAL1_LITERAL1(interp::REAL1_LITERAL1* i) const;

	interp::REAL3_LITERAL* getREAL3_LITERAL(coords::REAL3_LITERAL* c) const;
	coords::REAL3_LITERAL* getREAL3_LITERAL(interp::REAL3_LITERAL* i) const;

	void putREAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(coords::REAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* key, interp::REAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* val);
	interp::REAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* getREAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(coords::REAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* c) const;
	coords::REAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* getREAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(interp::REAL3_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* i) const;

	void putREAL3_LITERAL3(coords::REAL3_LITERAL3* key, interp::REAL3_LITERAL3* val);
	interp::REAL3_LITERAL3* getREAL3_LITERAL3(coords::REAL3_LITERAL3* c) const;
	coords::REAL3_LITERAL3* getREAL3_LITERAL3(interp::REAL3_LITERAL3* i) const;

	interp::REAL4_LITERAL* getREAL4_LITERAL(coords::REAL4_LITERAL* c) const;
	coords::REAL4_LITERAL* getREAL4_LITERAL(interp::REAL4_LITERAL* i) const;

	void putREAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(coords::REAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* key, interp::REAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* val);
	interp::REAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* getREAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(coords::REAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* c) const;
	coords::REAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* getREAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(interp::REAL4_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* i) const;

	void putREAL4_LITERAL4(coords::REAL4_LITERAL4* key, interp::REAL4_LITERAL4* val);
	interp::REAL4_LITERAL4* getREAL4_LITERAL4(coords::REAL4_LITERAL4* c) const;
	coords::REAL4_LITERAL4* getREAL4_LITERAL4(interp::REAL4_LITERAL4* i) const;

	interp::REALMATRIX_LITERAL* getREALMATRIX_LITERAL(coords::REALMATRIX_LITERAL* c) const;
	coords::REALMATRIX_LITERAL* getREALMATRIX_LITERAL(interp::REALMATRIX_LITERAL* i) const;

	void putREALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR(coords::REALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR* key, interp::REALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR* val);
	interp::REALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR* getREALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR(coords::REALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR* c) const;
	coords::REALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR* getREALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR(interp::REALMATRIX_LIT_REAL3_EXPR_REAL3_EXPR_REAL3_EXPR* i) const;

	void putREALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(coords::REALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* key, interp::REALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* val);
	interp::REALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* getREALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(coords::REALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* c) const;
	coords::REALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* getREALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR(interp::REALMATRIX_LIT_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR_REAL1_EXPR* i) const;

	void putREALMATRIX_LITERAL9(coords::REALMATRIX_LITERAL9* key, interp::REALMATRIX_LITERAL9* val);
	interp::REALMATRIX_LITERAL9* getREALMATRIX_LITERAL9(coords::REALMATRIX_LITERAL9* c) const;
	coords::REALMATRIX_LITERAL9* getREALMATRIX_LITERAL9(interp::REALMATRIX_LITERAL9* i) const;

private:

	std::unordered_map <coords::PROGRAM*,	interp::PROGRAM*	> 	coords2interp_PROGRAM;
	std::unordered_map <interp::PROGRAM*,	coords::PROGRAM*	> 	interp2coords_PROGRAM;

	std::unordered_map <coords::GLOBALSTMT*,	interp::GLOBALSTMT*	> 	coords2interp_GLOBALSTMT;
	std::unordered_map <interp::GLOBALSTMT*,	coords::GLOBALSTMT*	> 	interp2coords_GLOBALSTMT;

	std::unordered_map <coords::STMT*,	interp::STMT*	> 	coords2interp_STMT;
	std::unordered_map <interp::STMT*,	coords::STMT*	> 	interp2coords_STMT;

	std::unordered_map <coords::IFCOND*,	interp::IFCOND*	> 	coords2interp_IFCOND;
	std::unordered_map <interp::IFCOND*,	coords::IFCOND*	> 	interp2coords_IFCOND;

	std::unordered_map <coords::EXPR*,	interp::EXPR*	> 	coords2interp_EXPR;
	std::unordered_map <interp::EXPR*,	coords::EXPR*	> 	interp2coords_EXPR;

	std::unordered_map <coords::ASSIGNMENT*,	interp::ASSIGNMENT*	> 	coords2interp_ASSIGNMENT;
	std::unordered_map <interp::ASSIGNMENT*,	coords::ASSIGNMENT*	> 	interp2coords_ASSIGNMENT;

	std::unordered_map <coords::DECLARE*,	interp::DECLARE*	> 	coords2interp_DECLARE;
	std::unordered_map <interp::DECLARE*,	coords::DECLARE*	> 	interp2coords_DECLARE;

	std::unordered_map <coords::REAL1_EXPR*,	interp::REAL1_EXPR*	> 	coords2interp_REAL1_EXPR;
	std::unordered_map <interp::REAL1_EXPR*,	coords::REAL1_EXPR*	> 	interp2coords_REAL1_EXPR;

	std::unordered_map <coords::REAL3_EXPR*,	interp::REAL3_EXPR*	> 	coords2interp_REAL3_EXPR;
	std::unordered_map <interp::REAL3_EXPR*,	coords::REAL3_EXPR*	> 	interp2coords_REAL3_EXPR;

	std::unordered_map <coords::REAL4_EXPR*,	interp::REAL4_EXPR*	> 	coords2interp_REAL4_EXPR;
	std::unordered_map <interp::REAL4_EXPR*,	coords::REAL4_EXPR*	> 	interp2coords_REAL4_EXPR;

	std::unordered_map <coords::REALMATRIX_EXPR*,	interp::REALMATRIX_EXPR*	> 	coords2interp_REALMATRIX_EXPR;
	std::unordered_map <interp::REALMATRIX_EXPR*,	coords::REALMATRIX_EXPR*	> 	interp2coords_REALMATRIX_EXPR;

	std::unordered_map <coords::REAL1_VAR_IDENT*,	interp::REAL1_VAR_IDENT*	> 	coords2interp_REAL1_VAR_IDENT;
	std::unordered_map <interp::REAL1_VAR_IDENT*,	coords::REAL1_VAR_IDENT*	> 	interp2coords_REAL1_VAR_IDENT;

	std::unordered_map <coords::REAL3_VAR_IDENT*,	interp::REAL3_VAR_IDENT*	> 	coords2interp_REAL3_VAR_IDENT;
	std::unordered_map <interp::REAL3_VAR_IDENT*,	coords::REAL3_VAR_IDENT*	> 	interp2coords_REAL3_VAR_IDENT;

	std::unordered_map <coords::REAL4_VAR_IDENT*,	interp::REAL4_VAR_IDENT*	> 	coords2interp_REAL4_VAR_IDENT;
	std::unordered_map <interp::REAL4_VAR_IDENT*,	coords::REAL4_VAR_IDENT*	> 	interp2coords_REAL4_VAR_IDENT;

	std::unordered_map <coords::REALMATRIX_VAR_IDENT*,	interp::REALMATRIX_VAR_IDENT*	> 	coords2interp_REALMATRIX_VAR_IDENT;
	std::unordered_map <interp::REALMATRIX_VAR_IDENT*,	coords::REALMATRIX_VAR_IDENT*	> 	interp2coords_REALMATRIX_VAR_IDENT;

	std::unordered_map <coords::REAL1_LITERAL*,	interp::REAL1_LITERAL*	> 	coords2interp_REAL1_LITERAL;
	std::unordered_map <interp::REAL1_LITERAL*,	coords::REAL1_LITERAL*	> 	interp2coords_REAL1_LITERAL;

	std::unordered_map <coords::REAL3_LITERAL*,	interp::REAL3_LITERAL*	> 	coords2interp_REAL3_LITERAL;
	std::unordered_map <interp::REAL3_LITERAL*,	coords::REAL3_LITERAL*	> 	interp2coords_REAL3_LITERAL;

	std::unordered_map <coords::REAL4_LITERAL*,	interp::REAL4_LITERAL*	> 	coords2interp_REAL4_LITERAL;
	std::unordered_map <interp::REAL4_LITERAL*,	coords::REAL4_LITERAL*	> 	interp2coords_REAL4_LITERAL;

	std::unordered_map <coords::REALMATRIX_LITERAL*,	interp::REALMATRIX_LITERAL*	> 	coords2interp_REALMATRIX_LITERAL;
	std::unordered_map <interp::REALMATRIX_LITERAL*,	coords::REALMATRIX_LITERAL*	> 	interp2coords_REALMATRIX_LITERAL;
};

} // namespace

#endif